services:
  grafana:
    extends:
      file: .config/compose-base.yaml
      service: grafana

    volumes:
      - ./dist:/var/lib/grafana/plugins/embraceio-metric-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/embraceio-metric-app