{
 "title": "Embrace Metrics API Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_id", "query": { "query": "app_label" } },
   { "name": "interval", "query": "5m,60m,90m,2hr,4hr,6hr,12hr,1d" },
   { "name": "source", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "![icon]( https://embrace.io/images/embrace_color_logo.png )"
   }
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sessions By App Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Session Totals Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\"}) by (app_version, os_version)"
    }
   ]
  },
  {
   "title": "Crash Free Session %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(hourly_crashes_total{app_id=\"$app_id\"})\n/\n(sum(hourly_sessions_total{app_id=\"$app_id\"}))) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sessions By App Version, OS Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\"}) by (app_version, os_version)",
     "legendFormat": "{{app_version}} - {{os_version}}"
    }
   ]
  },
  {
   "title": "Sessions by Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\"}) by (device_model) "
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\"})"
    }
   ]
  },
  {
   "title": "Sessions for two app versions",
   "type": "timeseries",
   "description": "Override the app version in the PromQL",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\", app_version=\"app_version_1\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(hourly_sessions_total{app_id=\"$app_id\", app_version=\"app_version_2\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sessions for two app versions Note",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "options": {
    "content": "Override the app versions in the \"Sessions for two app versions\" with your own app versions.\n\nFor example, change\n```\nsum(hourly_sessions_total{app_id=\"$app_id\", app_version=\"app_version_1\"}) by (app_version)\n```\nto \n```\nsum(hourly_sessions_total{app_id=\"$app_id\", app_version=\"1.2.3\"}) by (app_version)\n```\n"
   }
  },
  { "title": "Crashes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Crashes By App Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(hourly_crashes_total{app_id=\"$app_id\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Crash Count By App Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum(hourly_crashes_total{app_id=\"$app_id\"}) by (app_version) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Crashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "sum(hourly_crashes_total{app_id=\"$app_id\"})"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Users By App Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(hourly_users{app_id=\"$app_id\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Crashed Users Total By App Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(hourly_crashed_users{app_id=\"$app_id\"}) by (app_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum(hourly_users{app_id=\"$app_id\"})"
    }
   ]
  }
 ]
}